### ISSUE TITLE
I use MagicBottle1.5.0 in 1.12.2 paper server some bug

### ISSUE THREAD

**Issue by FastChen** [Vontus/MagicBottle#27]
Very strange ,i load 1 - 48 plugins the MagicBottle is work normal
but plugins 48+ no matter plugin  the MagicBottle is not work
i don't no why no err in console, all plugins no err in console
only use 48+ plugins MagicBottle is not normal work but but can display text ,cannot store exp
Please check

1.12.2 paperspigot lastbuild ver

**Comment by Vontus** [comment]
I need some more information to know what could be causing this. Please share the list of plugins you're using and MagicBottle's config file.

**Comment by FastChen** [comment]
download link [onedrive](https://1drv.ms/u/s!AoU3H0aBv334kCvcgF-UQRshuXoo?e=IlZ5pC)


 --------------------- MagicBottle Configuration ---------------------
 If you misspell a value the configuration will be incorrect and the plugin won't load.
 If MagicBottle can't load, it is possible that something in this file is wrong. Please check that the indentation is correct and no TABs are used, only spaces.
 For an explanation of how .yml (YAML) files work, visit https://github.com/Animosity/CraftIRC/wiki/Complete-idiot%27s-introduction-to-yaml
 I don't think you're an idiot.
 ------------------------------------------------------------------

 Config:

 Enable or disable sound and particle effects when a MagicBottle is used.
effect:
  sound: true
  particles: true

recipe:
   Enable or disable the ability to fill or pour the bottle by using it in a crafting grid.
   You must restart your server after changing any of the recipes configurations.
  deposit: true
  withdraw: true
   Enable the ability to craft new MagicBottles.
   If you disable this, players won't be able to craft new bottles but existing ones will remain.
  bottle:
    enabled: true
     The recipe to craft a new empty MagicBottle.
     Don't modify the numbers or the order, just the content.
     Each slot in the crafting table is numbered from left to right and top to bottom (1 to 9).
     You can see a complete list of possible item names here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
     You can set AIR for an empty slot.
    recipe:
      1: ENDER_PEARL
      2: DIAMOND
      3: ENDER_PEARL
      4: GOLD_INGOT
      5: GLASS_BOTTLE
      6: GOLD_INGOT
      7: BOOK
      8: BOOK
      9: BOOK

 Set the maximum level a player can save in a single MagicBottle.
 TIP: Set this depending on how difficult you made the recipe.
max level:
   This will be applied when the player doesn't have any of the following permissions.
  default: 80
  permissions:
     Allow players to have bottles with more levels than the default option.
     To remove the limit entirely, give people 'magicbottle.maxlevel.unlimited'; still, the maximum level a bottle can hold is 20,000.
     You need to grant people the permission 'magicbottle.maxlevel.<name>', being <name> in the list shown below.
     If a player has two or more of these permissions, the maximum value will be applied, including 'magicbottle.maxlevel.unlimited'.
       For example, a Veteran user can have the permissions 'user' and 'veteran', but only 'veteran' will be applied.
     You can modify, add or remove any of the following limits at will.
    vip: 100
    vip+: 150
    mvp: 200
    mvp+: 300

repair:
   Enable or disable the '/mb repair' command
  enabled: true
   Enable or disable the '/mb repair auto' command
  auto: true
   Tools and armor will need this enchantment in order to be able to repair them
   Set this to ANY if you want MagicBottle to repair any repairable tool (unenchanted tools will be repaired too)
  enchantment: MENDING

 Here you can configure what percentage of experience will be charged when transferring experience.
costs:
  deposit:
     Integer from 0 to 100.
     Values from 50 to 100 might take experience without saving any in the bottle.
     I'd recommend using a value from 0 to 49.
    exp-percentage: 0
  craft new bottle:
     Money needed to create a new bottle. Vault is required for this to take effect.
    money: 0
     Whether to change the bottle lore when it is about to be crafted to tell the player how much it will cost.
     Enable this if you set a cost. The custom lore is in messages.yml
     Restart the server after changing this.
    change lore: false

 These compatibility settings that will try to disable things in the plugin that may break with other plugins
 You should only change them if you're having trouble
compatibility:
   Set this to true if your bottles stop working
   Bottles will show the enchantment 'Efficiency I' instead
  disable custom enchantments: false

 DON'T TOUCH THIS
config version: 0

**Comment by Vontus** [comment]
Try setting `compatibility.disable custom enchantments` to `true` at line 86 and restart the server.

**Comment by FastChen** [comment]
thx the problem is be solve
Thank you for making this good plugin
